### ISSUE TITLE
Copy Offload - Unique return code for create request with invalid file systems

### ISSUE THREAD

**Issue by NateRoiger** [NearNodeFlash/nnf-dm#25]
Expand the create response to return a unique failure if an offload create request is submitted to an invalid file system type (XFS/raw)

**Comment by bdevcich-hpe** [comment]
`DataMovementCreateResponse` will be updated to add `INVALID` to `status` along with a descriptive `message` to indicate an invalid filesystem was requested.

```protobuf
message DataMovementCreateResponse {
    string uid = 1;

    enum Status {
        SUCCESS = 0;
        FAILED = 1;
        INVALID = 2;
    }
    Status status = 2;
    string message = 3;
}
```
