### ISSUE TITLE
Data Movement v2

### ISSUE THREAD

**Issue by NateRoiger** [NearNodeFlash/nnf-dm#30]
Over the course of implementing data movement there were several observations and lessons learned along the way

1. Large complexity supporting the two implementations (Lustre and rsync). This leads to a large development burden, particularly as new features like #23 and #24 are developed.
2. There is a large complexity and startup cost using the [MPI Operator from Kubeflow](https://github.com/kubeflow/mpi-operator) - each node must be assigned a label, the MPI workers pods must start, k8s must assign DNS names to each pod, and finally the launcher pod starts. I've seen this take 30+ seconds on occasion (10-15s on average), which could be greater than the file transfer time in some cases!
3. LLNL has raised concerns about using rsync as it is single threaded, particularly for large directory trees as used in NNF08. Parallel execution wrapper around rsync is possible, but that doesn't address issues 1 or 2.

## v2 Goals

To address these issues with the v1 implementation, I am proposing v2 aimed at these goals:

1. Unifies the code under one implementation using mpiFileUtils
2. Allows for parallel execution on a single node using MPI slots
3. Avoids the startup cost of MPI Operator

These goals are achieved with the following implementation highlights:

1. One MPI Worker pod per Rabbit that never exits - something very similar is already done for the rsync implementation
2. Each Data Movement resource executes the mpirun with the --hosts argument, targeting the desired Rabbits/MPI Workers - this leverages the MPI Operator code. If 2 or more slots are required then a --hostfile can be used.

## Concerns

There is one concerns for this implementation that I can come up with (beyond the development effort)

1. MPI overhead - Are there valid use cases (i.e. few/small files) where starting an mpirun operation is _more_ overhead then rsync? 

### Data Movement Resource
The data movement custom resource remains unchanged in format. The data movement controller is re-written to execute the mpirun command. This command requires....

1. A --hosts argument used to target the specific Rabbit nodes. The data movement controller will translate a Rabbit Node Name to the corresponding MPI Worker pod
2. That proper SSH keys are loaded to communicate with the work pods. This requires the data movement controller to be launched with the correct Secrets in the deployment specification

### MPI Worker Pods
One MPI Worker pod will run for each Rabbit using a Kubernetes DaemonSet with the necessary NodeSelector & Toleration as done elsewhere in nnf-sos and nnf-dm (for the rsync implementation). The DaemonSet would contain the global Lustre mounts. Ephemeral Lustre would require the Lustre mount is present in the /mnt directory. 

Worker pods are started running sshd in a detached state (/usr/sbin/sshd -De)

### SSH Keys
MPI uses SSH to start remote programs from the launcher. We therefore need to share keys amongst the workers and launcher pods. 

MPI Operator accomplishes this by generating SSH keys and creating Kubernetes Secrets with both private and public key. When creating the worker and launcher pods, the secrets are mounted into the id_rsa, id_rsa.pub, and authorized_keys files.

The v2 implementation closely parallels this, with the DaemonSet describing the worker pods containing the same Cmd and Volume mounts as used by MPI Operator

### Initializing Data Movement Deployment and Worker Pods
As covered earlier, a Kubernetes Secret representing the RSA security keys must be shared between launcher and worker pods. This requires a bootstrapping of the pods having created the secrets earlier.

The picture below highlights both the bootstrapping process (red) and an example data movement operation (blue)
![nnf-dm-v2 (1)](https://user-images.githubusercontent.com/546438/182243244-c2820ea8-3d48-4347-ba3d-f10d5547bce5.png)

**Comment by NateRoiger** [comment]
@behlendorf I think this is a worthy project, but wanted your review first; particularly the concern in converting fully to using mpiFileUtils. For a few small files I think the overhead of starting an mpirun command might be greater than rsync. But if that's not a priority, then I think this would benefit the more common use cases.

We had talked about an "extremely large file" use case and possibly partitioning the file. While this wouldn't immediately solve that problem I think adding optimizations to mpiFileUtils could.

**Comment by behlendorf** [comment]
@NateRoiger using MPIFileUtils for all data transfers seems strikes me as a nice simplification and I believe it should be a performance win for most of our common workloads.  Plus as you pointed out it opens to door to adding whatever optimizations we might need to MPIFileUtils.  It's already aware of different filesystem types and I could see us extending that further. 

That's all great, but one potential concern I have is that it was my understanding in the v1 design the pod was launched as the unprivileged user who requested the data movement.  That acted as an extra safeguard that only their data could be accessed.  With a long running pod it sounds like we're now depending on `mpirun` to execute MPIFileUtils as the correct user in the pod.  In which case can we still use an unprivileged container?  How would this now be handled?

**Comment by NateRoiger** [comment]
Can we execute mpirun with the user's credentials as we did with rsync? I'm not sure if Open MPI will start the workers with the same privileges (and I'm not finding much searching online).

https://github.com/NearNodeFlash/nnf-dm/blob/a274c735401102484426b042610727aab513d392/controllers/rsyncnodedatamovement_controller.go#L122-L127

**Comment by ofaaland** [comment]
@NateRoiger When the user indicates via ```#DW``` that they need a file system, and then use that ```name``` later in offload requests, is the name they provide required to be globally unique within the system, so the mountpoints wouldn't have name conflicts?  I know we discussed this but can't find the conclusion.

**Comment by NateRoiger** [comment]
@ofaaland The mount point is nested under the job ID to avoid naming conflicts, something like `/mnt/nnf/[job-id]/[name]`

**Comment by NateRoiger** [comment]
@behlendorf I might have a solution, but it will require an enhancement to mpiFileUtils.

If we grant mpiFileUtils with SETUID/SETGID capabilities in the Docker image, and then mpiFileUtils adds command line options for uid/gid and applies them to setuid()/setgid() system calls, we would then be safe - even if the pods are run as root. Data movement would always provide a uid/gid so there's no backdoor for a user to skip those params.

**Comment by behlendorf** [comment]
@NateRoiger that sounds like it might be workable.  If so, then it seems like using `sudo -u <uid>` could also be a viable alternative to running with the user permissions.  A couple nice things about using `sudo` is it would avoid the need for a setuid/setgid binary, it's possible to precisely control what can be run by whom, and it would provide for an audit log if needed.  On the flip side, by design it's tricky to preserve environment variables but I'm not sure if that would be an issue.

One thing I'm still not clear on through is exactly how this command would get invoked in these long running containers.  Would you mind describing how that works, perhaps better yet point me at the relevant bit of code?

For this to work it also seems like there needs to be some mechanism to synchronize the uid/gids in the containers with those on the host.  I'm not quite sure what best practices are in this regard.

**Comment by NateRoiger** [comment]
@behlendorf I wasn't able to get `sudo -u <uid>` working, at least running as root. I can run-as-root to the local host, but if I specify multiple hosts it fails. Because of this I went down the setuid/setgid route, but if you can advise how this might work using `sudo` I can continue to explore it.
```
# mpirun --host=rabbit-compute-4 --allow-run-as-root /tmp/mpi_hello_world
Hello world from processor rabbit-compute-4, rank 0 out of 1 processors, uid 1002
```

```
# mpirun -np 4 --host=rabbit-compute-4,rabbit-compute-5  --allow-run-as-root /tmp/mpi_hello_world
--------------------------------------------------------------------------
An unrecognized option was included on the prted command line:

  Option: --allow-run-as-root

Please use the "prted --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
prterun was unable to reliably start one or more daemons.
This usually is caused by:
[...]
```



> One thing I'm still not clear on through is exactly how this command would get invoked in these long running containers. Would you mind describing how that works, perhaps better yet point me at the relevant bit of code?

We would steal this bit from MPI Operator where a "worker" pod runs without exiting by [executing `sshd` in a detached state](https://github.com/kubeflow/mpi-operator/blob/993b010e05c48c6f6ef5a5180362ccd3e716982e/v2/pkg/controller/mpi_job_controller.go#L1249). Each worker pod is identified and reachable by a FQDN which kubernetes supports.

The "launcher" pod would be a long running pod that works to reconcile data-movement resources; each resource would correspond to an `mpirun` with --host or --hostfile options providing the desired workers (rabbits). This is similar to how we handle rsync today, where each rsync node resource is reconciled via a kubernetes controller that executes the [rsync command](https://github.com/NearNodeFlash/nnf-dm/blob/ccd47c490da72faa1e4caa66b01046d6b47a3c62/controllers/rsyncnodedatamovement_controller.go#L119-L131)

> For this to work it also seems like there needs to be some mechanism to synchronize the uid/gids in the containers with those on the host. I'm not quite sure what best practices are in this regard.

In my limited testing using `setuid`, the mpi executable could assume the uid without the uid being present on the host. So I don't think any mechanism needs to be present to populate the uid/gid to the containers.

```c
$ cat mpi_hello_world.c
// Author: Wes Kendall
// Copyright 2011 www.mpitutorial.com
// This code is provided freely with the tutorials on mpitutorial.com. Feel
// free to modify it for your own use. Any distribution of the code must
// either provide a link to www.mpitutorial.com or keep this header intact.
//
// An intro MPI hello world program that uses MPI_Init, MPI_Comm_size,
// MPI_Comm_rank, MPI_Finalize, and MPI_Get_processor_name.
//
#include <mpi.h>
#include <stdio.h>
#include <unistd.h>

int main(int argc, char** argv) {
  // Initialize the MPI environment. The two arguments to MPI Init are not
  // currently used by MPI implementations, but are there in case future
  // implementations might need the arguments.
  MPI_Init(NULL, NULL);

  // Get the number of processes
  int world_size;
  MPI_Comm_size(MPI_COMM_WORLD, &world_size);

  // Get the rank of the process
  int world_rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

  // Get the name of the processor
  char processor_name[MPI_MAX_PROCESSOR_NAME];
  int name_len;
  MPI_Get_processor_name(processor_name, &name_len);

  // TEST - Change UID to 1002
  setuid((uid_t) 1002);
  uid_t uid = getuid();

  // Print off a hello world message
  printf("Hello world from processor %s, rank %d out of %d processors, uid %d\n",
         processor_name, world_rank, world_size, uid);

  // Finalize the MPI environment. No more MPI calls can be made after this
  MPI_Finalize();
}
```

```
$ mpirun -np 2 --host=rabbit-compute-4,rabbit-compute-5 /tmp/mpi_hello_world
Hello world from processor rabbit-compute-4, rank 0 out of 2 processors, uid 1002
Hello world from processor rabbit-compute-5, rank 1 out of 2 processors, uid 1002
```

I think I might have time this week to start prototyping this. The good news is this would only change the internals of data-movement; so the copy-offload API and copy_in/copy_out directives don't have to change.

**Comment by behlendorf** [comment]
> I wasn't able to get sudo -u <uid> working, at least running as root.

This should be doable, but it sounds like a bit more investigation is needed.   In fact, it's my understanding the sudoers file could even be set up to allow a non-root user to run a specific command (mpirun) as another user.  We really don't want to use `--allow-run-as-root` if possible.  Unfortunately, I'm not sure exactly what your running in to.

>  So I don't think any mechanism needs to be present to populate the uid/gid to the containers.

As long as you're only using uid/gids in the containers that makes sense to me since it's all the kernel cares about.  We just won't be able to resolve user/group names.
