### ISSUE TITLE
Copy Offload - API function name change request for C client library

### ISSUE THREAD

**Issue by mcfadden8** [NearNodeFlash/nnf-dm#32]
The current c-client library uses function names that could collide with other libraries.  The API currently exports the following functions:

- `OpenConnection`
- `CloseConnection`
- `Create`
- `Status`
- `Delete`
- `Free`

Could these names be changed to include an `nnfdm` prefix (or something similar) in order to avoid collisions when built in to a larger program?  Perhaps somthing like: `nnfdmOpenConnection`, `nnfdmCloseConnection`, `nnfdmCreate`, `nnfdmStatus`, `nnfdmDelete`, and `nnfdmFree`?

**Comment by NateRoiger** [comment]
In using lib-cpp this becomes a non-issue (the library uses `near_node_flash::data_movement` namespace)
