### ISSUE TITLE
data mover daemon RPM build does not contain github commit hash

### ISSUE THREAD

**Issue by NateThornton** [NearNodeFlash/nnf-dm#84]
The RPM build does not provide the correct GitHub commit hash, so the daemon is reporting `v0.0.1-unknown`

When using the `build-daemon` make target, the commit hash is loaded from git https://github.com/NearNodeFlash/nnf-dm/blob/d5df11f4b1eaeabaf1857fc37d5dbde75439f4f6/Makefile#L123-L126

If this fails, the default value is "unknown" https://github.com/NearNodeFlash/nnf-dm/blob/d5df11f4b1eaeabaf1857fc37d5dbde75439f4f6/daemons/compute/server/version/version.go#L30

**Comment by bdevcich-hpe** [comment]
Closing this as @matthew-richerson merged #87.
