### ISSUE TITLE
Use hostfiles for mpirun to allow slot configuration

### ISSUE THREAD

**Issue by bdevcich-hpe** [NearNodeFlash/nnf-dm#85]
mpirun is configured with only 1 slot per host, so using --num-processes > NUM_HOSTS results in degraded mode. See more [here](https://www.open-mpi.org/faq/?category=running#oversubscribing).

On a system with 1 NNF node, that means we have 1 DM worker pod, which means we only have 1 host, and 1 slot available.

In order to set the number of slots available, a host file is required. There does not appear to be a command line option for slots. When using the `--host`  option, the number of slots is equal to the number of hosts supplied.  See [here](https://www.open-mpi.org/faq/?category=running#slots-without-hostfiles).

The hostfile looks like this:

```
hostname1 slots=N max_slots=Y
hostname2 slots=N max_slots=Y
...
```
More info: https://www.open-mpi.org/faq/?category=running#mpirun-hostfile

In order to experiment more with these values, I propose the following:

1. Change Data Movement to use `--hostfile` rather than `--host`
2. Allow the user to specify `slots` and `max_slots` for all hosts in the DM Config Map. These two values will have to be the same for every host due to the host list being dynamically generated based on the number of DM Worker pods.
3. Add another field in the DM Config Map to pass any additional parameters to `mpirun`

Using `slots: 4 and max_slots: 4`, the hostfile for a 2 NNF node system would be:

```
nnf-dm-worker-jd4rl slots=4 max_slots=4
nnf-dm-worker-nnvb7 slots=4 max_slots=4
```

Additional considerations:

How do we handle the cases when multiple DM progresses are running (i.e. multiple `mpirun` instances)? If we have a hostile that specifies 4 slots and 4 max slots on a DM Worker Pod that has 4 cores, what happens when another DM job comes along and requests the same? There would be two mpirun processes trying to use 8 slots on a 4 slot host.

If `slots`/`max_slots` are not defined, this could default to the number of cores available on the DM Worker pod.

**Comment by bdevcich-hpe** [comment]
@behlendorf Please consider what I've proposed. It might not be as simple as originally thought when you consider multiple data movements and the number of slots available. However, this might be enough to get started with more experimentation on this until we discover a more concrete solution.

**Comment by behlendorf** [comment]
> These two values will have to be the same for every host due to the host list being dynamically generated based on the number of DM Worker pods.

Can you explain this a bit more.  I'm not sure why both `slots` and `max_slots` would need to be the same.  In fact, most schedulers don't bother setting `max_slots` so the node can be oversubscribed.  Oversubscribing MFU might even be useful since I'd expect it spends the majority of its time blocked in IO system calls.

> what happens when another DM job comes along and requests the same?

Good question.  What you're proposing here should let us start experimenting so we can figure out what that default behavior should be.  We may determine that we really need to queue the data movement requests, or it may be that oversubscribing the node is fine in practice.

**Comment by bdevcich-hpe** [comment]
> Can you explain this a bit more. I'm not sure why both `slots` and `max_slots` would need to be the same. In fact, most schedulers don't bother setting `max_slots` so the node can be oversubscribed. Oversubscribing MFU might even be useful since I'd expect it spends the majority of its time blocked in IO system calls.

If you define these values in the config map, they will end up being applied to _all_ the hosts in the hostfile. I'm not saying that `slots` and `max_slots` don't need to be equal. The reasoning for this is that the list of hosts are dynamic so we wouldn't have a way to specify unique values for every host, so we'd have to blanket them on all the hosts.

So you wouldn't really be able to do something like this where you have different values for every host:

```
nnf-dm-worker-jd4rl slots=2 max_slots=4
nnf-dm-worker-nnvb7 slots=3 max_slots=6
```

But rather, if you specified slots=2 and max_slots=4 in the config map, those two values would be the same for every host:

```
nnf-dm-worker-jd4rl slots=2 max_slots=4
nnf-dm-worker-nnvb7 slots=2 max_slots=4
```

**Comment by behlendorf** [comment]
That makes sense.  For the moment, I think having the same values for every host should be fine.  Where this could end up being an issue long term is mixing multiple versions/configurations of NNF node hardware on the same system.

**Comment by NateThornton** [comment]
Blake, at the same time it might be worth tackling the following items

1. Move the config into the nnf-dm-system namespace and cleanup the deployment.
2. Allow custom command line parameters. This will allow customization of the mpirun params and dcp (useful for any enhancements to dcp that LLNL might provide, like generating completion files after the copy) so we don't need to deploy nnf-dm for every single change.

**Comment by bdevcich-hpe** [comment]
Based on our discussion today at the Flux meeting - we should also consider adding adjustments from the Copy Offload API. The Create Request could include additional slot/max_slot parameters along with any extra mpirun options.

**Comment by bdevcich-hpe** [comment]
@behlendorf: I've opened a PR to address this: https://github.com/NearNodeFlash/nnf-dm/pull/89.
