### ISSUE TITLE
Allow specific MPI configuration when using the Copy Offload API

### ISSUE THREAD

**Issue by bdevcich-hpe** [NearNodeFlash/nnf-dm#90]
Related to #85, allow Copy Offload Create Requests to specify slots, max_slots, and extra dcp/mpi options. This would override the default configuration defined by the `nnf-dm-config` ConfigMap.

**Comment by mcfadden8** [comment]
@bdevcich-hpe - Just checking, is the `nnf-dm-config` ConfigMap what is set up in the hostfiles slot configuration as discussed in #85?   I believe this to be the case and that this is just a way to override it?

**Comment by mcfadden8** [comment]
Okay, thanks for the clarification.  At least for now,  I think that the default values in Config may be sufficient.  If I understand correctly, I think we may need other changes in the Copy Offload API or implementation.  It would probably be best to discuss this in #88

**Comment by bdevcich-hpe** [comment]
Closing this one for now. We can always reopen if need be.
